### ISSUE TITLE
Precompiled version

### ISSUE THREAD

**Issue by imriss** [brainbuz/String-Validator#1]
I have a system where I cannot install `make`. Is there any precompiled version of this modules available somewhere, so I can deploy the modules to that system without the need to install `build-essentials`? Or, is there a way so I can compile the modules on another system with `make`, and then transfer them?

Thanks

**Comment by brainbuz** [comment]
Install String::Validator::Password instead of String::Validator. The root String::Validator Module installs all of the current Validators in the family some of which have non-core dependencies, Password and Common (the base module) have no non-core dependencies, if the cpan utiltiy you use can install other Pure Perl modules from cpan it should work.

cpanm String::Validator::Password

If that doesn't work try installing String::Validator::Password and
String::Validator::Common by hand into your  `@INC`  path. You should be able to find documentation elsewhere on how to do that since that's a generic perl issue.

FYI, release 2.0 is imminent and adds supports for language customization of the messages, if you are fluent in languages other than english I would appreciate if you would be willing to help translate.

**Comment by brainbuz** [comment]
Repackaging perl modules is up to the distribution not the capn author. String Validator's Common and Password modules have combined near perfect cpan testers results for both the current version and the prior stable version. Installing them is standard perl administration

FYI the new version did change some of the base messages, so your developer should check to see if it creates any problems. The old versions are still up on cpan if you need to install them, and again it is well documented elsewhere how to install specific versions of modules.
